name: ezy_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: any
  flutter_bloc: any
  uuid: any
  flex_color_picker: any
  url_launcher: any
  hive: any
  hive_flutter: any
  data_table_2: ^2.5.15
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any
  flutter_lints: ^3.0.0
  build_web_compilers: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/utils/constants/strings/string_value.json
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
